---

- name: Create user "{{ service_user }}"
  ansible.builtin.user:
    name: "{{ service_user }}"
    groups: wheel, mock
    append: yes
    state: present
    create_home: yes
    generate_ssh_key: yes

- name: Create subsequent directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    recurse: yes
    owner: "{{ service_user }}"
    group: "{{ service_group }}"
  with_items: "{{ working_directories }}"

- name: Generate build node config
  ansible.builtin.template:
    src: build_node.j2
    dest: "{{ final_conf_dir }}/build_node.yml"
    owner: "{{ service_user }}"
    group: "{{ service_group }}"
    mode: "0644"

- name: Clone albs-node repository
  become: yes
  become_user: "{{ service_user }}"
  ansible.builtin.git:
    repo: https://github.com/AlmaLinux/albs-node.git
    dest: "{{ build_node_working_directory }}/albs-node"
    clone: yes
    update: yes
    accept_hostkey: yes
    force: yes

- name: Create Python virtual environment
  become: yes
  become_user: "{{ service_user }}"
  ansible.builtin.command: python3 -m venv --system-site-packages "{{ build_node_venv_directory }}"
  args:
    creates: "{{ build_node_venv_directory }}/bin/activate"

- name: Upgrade pip in virtualenv
  become: yes
  become_user: "{{ service_user }}"
  ansible.builtin.command: "{{ build_node_venv_directory }}/bin/pip install --upgrade pip"

- name: Install requirements into virtualenv
  become: yes
  become_user: "{{ service_user }}"
  ansible.builtin.pip:
    requirements: "{{ build_node_requirements_path }}"
    virtualenv: "{{ build_node_venv_directory }}"
...
