---

- name: Update system packages
  ansible.builtin.dnf:
    name: "*"
    state: latest
  register: update_state

- name: Reboot a machine
  ansible.builtin.reboot:
    reboot_timeout: 180
  when: update_state.changed

- name: Install epel repository
  ansible.builtin.dnf:
    name: epel-release
    state: latest

- name: Install build system repository
  ansible.builtin.yum_repository:
    name: "buildnode"
    file: "buildnode"
    description: "Repository with dependencies for albs-node code"
    baseurl: https://repo.almalinux.org/build_system/{{ os_version }}/$basearch/
    enabled: no
    gpgcheck: no

- name: Install required system packages packages
  ansible.builtin.dnf:
    name: "{{ build_node_dnf_packages }}"
    state: latest
    enablerepo:
      - epel
      - buildnode
      - "{{ powertools_repository_name }}"
    update_cache: yes
...
