---
- name: Deploy the ALBS
  hosts: albs_vm
  roles:
    - dev_deploy
  tags:
    - web-server-deploy
  connection: "{{ 'local' if use_local_connection else 'ssh' }}"

- name: Deploy the separate build node of ALBS
  hosts: build_node_vm
  roles:
    - separate_build_node
  tags:
    - build-node-deploy
  connection: "{{ 'local' if use_local_connection else 'ssh' }}"
...
