---
threads_count: 4
base_work_dir: "/srv/alternatives"
home_dir: "/home/{{ service_user }}"
base_conf_dir: "{{ home_dir }}/.config"
final_conf_dir: "{{ base_conf_dir }}/castor"
service_user: albs-builder
service_group: albs-builder
build_node_working_directory: "{{ home_dir }}/albs"
build_node_venv_directory: "{{ home_dir }}/.builder-venv"
build_node_requirements_path: "{{ build_node_working_directory }}/albs-node/requirements.txt"
powertools_repository_name: crb
working_directories:
  - "{{ base_work_dir }}"
  - "{{ build_node_working_directory }}"
  - "{{ base_work_dir }}/castor/build_node"
  - "{{ base_work_dir }}/castor/build_node/mock_configs"
  - "{{ final_conf_dir }}"
...
